#!/usr/bin/env node
// Scansiona dist/frontend/** + i font Excalidraw e genera
// src/canvas-app/embedded-frontend.ts con un import per ogni asset.
// Eseguito prima di `bun build --compile` in scripts/build-bin.ts.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');

const FRONTEND_DIR = path.join(PROJECT_ROOT, 'dist', 'frontend');
const FONTS_DIR = path.join(
  PROJECT_ROOT,
  'node_modules',
  '@excalidraw',
  'excalidraw',
  'dist',
  'prod',
  'fonts',
);
const OUTPUT = path.join(PROJECT_ROOT, 'src', 'canvas-app', 'embedded-frontend.ts');

interface Entry {
  relImport: string;
  varName: string;
  urlPath: string;
}

function walkFiles(dir: string, baseUrl: string): { absPath: string; urlPath: string }[] {
  const out: { absPath: string; urlPath: string }[] = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const url = path.posix.join(baseUrl, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkFiles(abs, url));
    } else if (entry.isFile()) {
      out.push({ absPath: abs, urlPath: url });
    }
  }
  return out;
}

function sanitizeVarName(rel: string): string {
  return '_' + rel.replace(/[^A-Za-z0-9]/g, '_');
}

function main(): void {
  if (!fs.existsSync(FRONTEND_DIR)) {
    console.error(`[gen:embedded] ERROR: ${FRONTEND_DIR} not found. Run \`npm run build:frontend\` first.`);
    process.exit(1);
  }

  const entries: Entry[] = [];
  const seen = new Set<string>();
  const embeddedFileDir = path.dirname(OUTPUT);

  for (const { absPath, urlPath } of walkFiles(FRONTEND_DIR, '/')) {
    const relImport = path
      .relative(embeddedFileDir, absPath)
      .split(path.sep)
      .join('/');
    let varName = sanitizeVarName(urlPath);
    while (seen.has(varName)) varName = varName + '_';
    seen.add(varName);
    entries.push({ relImport: relImport.startsWith('.') ? relImport : './' + relImport, varName, urlPath });
  }

  for (const { absPath, urlPath } of walkFiles(FONTS_DIR, '/assets/fonts/')) {
    const relImport = path
      .relative(embeddedFileDir, absPath)
      .split(path.sep)
      .join('/');
    let varName = sanitizeVarName(urlPath);
    while (seen.has(varName)) varName = varName + '_';
    seen.add(varName);
    entries.push({ relImport: relImport.startsWith('.') ? relImport : './' + relImport, varName, urlPath });
  }

  const banner = [
    '// AUTO-GENERATED by scripts/generate-embedded-frontend.ts — DO NOT EDIT.',
    '// Regenerate with: npm run gen:embedded',
    '',
  ].join('\n');

  const imports = entries
    .map((e) => `import ${e.varName} from '${e.relImport}' with { type: 'file' };`)
    .join('\n');

  const map = entries
    .map((e) => `  '${e.urlPath}': ${e.varName},`)
    .join('\n');

  const body = `
import { file } from 'bun';

const paths: Record<string, string> = {
${map}
};

/** Ritorna un Bun.file() per il path HTTP richiesto, o null. */
export function getEmbeddedFile(urlPath: string): ReturnType<typeof file> | null {
  const normalized = urlPath === '/' ? '/index.html' : urlPath.split('?')[0];
  const p = paths[normalized];
  return p ? file(p) : null;
}

export const embeddedPaths = paths;
`;

  const content = banner + imports + '\n' + body;
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, content);
  console.log(`[gen:embedded] Wrote ${entries.length} entries to ${path.relative(PROJECT_ROOT, OUTPUT)}`);
}

main();
